config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'home#index'
    resources :products,   only: [:show]
    resources :categories, only: [:show]

    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/option_type_decorator.rb
Spree::OptionType.class_eval do
  scope :specified_by_presentation, -> (presentation) { where(presentation: presentation)  }
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  scope :without_product,              -> (product) {
    where.not(id: product.id)
  }
  scope :join_taxons_and_specified_by, -> (taxons)  {
    joins(:taxons)
    .where(spree_taxons: {id: taxons})
  }
  scope :related_products,             -> (product) {
    join_taxons_and_specified_by(product.taxons)
    .without_product(product)
    .distinct
    .includes(master: [:default_price, :images])
  }
  scope :order_by_latest,              -> {
    order(available_on: :desc)
  }
  scope :available_within_past,        -> (time) {
    where('available_on > ?', time.ago)
  }
  scope :order_by_latest_within_past,  -> (time) {
    available_within_past(time)
    .order_by_latest
  }
  scope :filter_by_options,            -> (options) {
    joins(variants: :option_values)
    .where(spree_option_values: { name: options[:option_value] }) if options[:option_value].present?
  }

  scope :filter_by_taxon,              -> (taxon) {
    includes(master: [:default_price, :images])
    .in_taxon(taxon)
  }

  scope :count_products_by,            -> (taxon_id, value) {
    includes(variants: :option_values)
    .in_taxon(Spree::Taxon.find(taxon_id))
    .where(spree_option_values: { name: value.name })
    .count
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  before_action :set_root_taxons, :set_filter_color, :set_filter_size
  helper_method :the_number_of_products_by

  def show
    @taxon = Spree::Taxon.find(params[:id])
    @value = filter_params[:option_value]
    @category = Spree::Product
                  .filter_by_taxon(@taxon)
                  .filter_by_options(filter_params)
  end

  private

    def filter_params
      { option_type: params[:option_type], option_value: params[:option_value] }
    end

    def the_number_of_products_by(value)
      Spree::Product
        .count_products_by(params[:id], value)
    end

    def set_root_taxons
      @root_taxons = Spree::Taxon.roots
    end

    def set_filter_color
      @option_type_colors = Spree::OptionType
                              .includes(:option_values)
                              .specified_by_presentation("color")
    end

    def set_filter_size
      @option_type_sizes = Spree::OptionType
                            .includes(:option_values)
                            .specified_by_presentation("size")
    end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  THE_NUMBER_OF_PRODUCTS = 8
  HOW_MANY_MONTHS_AGO    = 3.months

  def index
    @latest_products = Spree::Product.includes(master: [:default_price, :images])
                        .order_by_latest_within_past(HOW_MANY_MONTHS_AGO)
                        .limit(THE_NUMBER_OF_PRODUCTS)
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  THE_NUMBER_OF_PRODUCTS = 4

  def show
    @product = Spree::Product.find(params[:id])
    @images  = @product.images
    @product_properties = @product.product_properties.includes(:property)
    @related_products   = Spree::Product
                            .related_products(@product)
                            .limit(THE_NUMBER_OF_PRODUCTS)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "BIGBAG Store"
    if page_title.empty?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end

  def page_title(taxon, value)
    if value.nil?
      taxon.name
    else
      "#{taxon.name} / #{value}"
    end
  end
end

app/views/filter/_area.html.erb
<div class="row filterArea">
  <div class="col-xs-6">
    <select name="guiest_id1" id="guiest_id1" class="select-drop">
      <option value="0">並び替え</option>
      <option value="1">人気順</option>
      <option value="2">安い順</option>
      <option value="3">新着順</option>
      <option value="3">高い順</option>
    </select>
  </div>
  <div class="col-xs-6">
    <div class="btn-group pull-right" role="group">
      <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
      <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
    </div>
  </div>
</div>

app/views/filter/_category.html.erb
<div class="panel panel-default">
  <div class="panel-heading">商品カテゴリー</div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">
        <% root_taxons.each do |root_taxon| %>
          <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#root_taxon<%= root_taxon.id %>"><%= root_taxon.name %><i class="fa fa-plus"></i></a>
            <ul id="root_taxon<%= root_taxon.id %>" class="collapse collapseItem">
              <% root_taxon.leaves.each do |leave_taxon| %>
                <li>
                  <%= link_to potepan_category_path(leave_taxon.id) do %>
                    <i class="fa fa-caret-right" aria-hidden="true"></i><%= leave_taxon.name %><span> ( <%= leave_taxon.products.count %> ) </span>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/filter/_color.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">
        <%= render partial: 'filter/option_type_nav', collection: @option_type_colors, as: 'option_type_nav' %>
      </ul>
    </div>
  </div>
</div>

app/views/filter/_option_type_nav.html.erb
<% option_type_nav.option_values.each do |option_value| %>
  <li>
    <%= link_to potepan_category_path(params[:id], option_type: option_type_nav.presentation, option_value: option_value.name) do %>
      <%= option_value.name %><span> ( <%= the_number_of_products_by(option_value) %> ) </span>
    <% end %>
  </li>
<% end %>

app/views/filter/_price.html.erb
<div class="panel panel-default priceRange">
  <div class="panel-heading">値段から探す</div>
  <div class="panel-body clearfix">
    <div class="price-slider-inner">
      <span class="amount-wrapper">
        <input type="text" id="price-amount-1" readonly>
        <strong>-</strong>
        <input type="text" id="price-amount-2" readonly>
      </span>
      <div id="price-range"></div>
    </div>
    <input class="btn btn-default" type="submit" value="絞り込む">
    <!-- <span class="priceLabel">Price: <strong>12 円- 30<円/strong></span> -->
  </div>
</div>

app/views/filter/_size.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">サイズから探す</div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">
        <%= render partial: 'filter/option_type_nav', collection: @option_type_sizes, as: 'option_type_nav' %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_copy_right.html.erb
<!-- COPY RIGHT -->
<div class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016 Copyright Bigbag Store Bootstrap Template by <a target="_blank" href="http://www.iamabdus.com/">Abdus</a>.</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
          <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
          <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<div class="footer clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Accessories</h5>
          <ul class="list-unstyled">
            <li><a href="#">Body care </a></li>
            <li><a href="#">Chambray </a></li>
            <li><a href="#">Floral </a></li>
            <li><a href="#">Rejuvination </a></li>
            <li><a href="#">Shaving </a></li>
            <li><a href="#">Toilette </a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>BRANDS</h5>
          <ul class="list-unstyled">
            <li><a href="#">Barbour </a></li>
            <li><a href="#">Brioni </a></li>
            <li><a href="#">Oliver Spencer</a></li>
            <li><a href="#">Belstaff</a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Accessories</h5>
          <ul class="list-unstyled">
            <li><a href="#">Body care </a></li>
            <li><a href="#">Chambray </a></li>
            <li><a href="#">Floral </a></li>
            <li><a href="#">Rejuvination </a></li>
            <li><a href="#">Shaving </a></li>
            <li><a href="#">Toilette </a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Get in Touch</h5>
          <ul class="list-unstyled">
            <li>Call us at (555)-555-5555</li>
            <li><a href="mailto:support@iamabdus.com">support@iamabdus.com</a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="newsletter clearfix">
          <h4>Newsletter</h4>
          <h3>Sign up now</h3>
          <p>Enter your email address and get notified about new products. We hate spam!</p>
          <div class="input-group">
            <input type="text" class="form-control" placeholder="your email address" aria-describedby="basic-addon2">
            <a href="#" class="input-group-addon" id="basic-addon2">go <i class="glyphicon glyphicon-chevron-right"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>
  <%= render 'layouts/shim' %>
</head>

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">
  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
            <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
            <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li><span><a data-toggle="modal" href='#login'>Log in</a><small>or</small><a data-toggle="modal" href='#signup'>Create an account</a></span></li>
            <li class="dropdown searchBox">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <span class="input-group">
                    <input type="text" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span class="input-group-addon" id="basic-addon2">Search</span>
                  </span>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-shopping-cart"></i>$0</a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>Item(s) in your cart</li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <div class="btn-group" role="group" aria-label="...">
                    <button type="button" class="btn btn-default">Shopping Cart</button>
                    <button type="button" class="btn btn-default">Checkout</button>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("img/logo.png", alt: "", class: "navbar-brand"), potepan_path %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="<%= "active" if params[:controller] == 'potepan/home' %>">
            <%= link_to "Home", potepan_path %></li>
          <li class="dropdown megaDropMenu <%= "active" if params[:controller] != 'potepan/home' %>">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
            <ul class="dropdown-menu row">
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products Grid View</li>
                  <% # TODO: 仮の対応としてカテゴリー一覧へのリンクにtaxon_id = 1のパスを設定。 %>
                  <li><%= link_to "Categories", potepan_category_path(1) %></li>
                  <li><a href="product-grid-right-sidebar.html">Products Sidebar Right</a></li>
                  <li><a href="product-grid-3-col-filter.html">Products 3 Columns V1</a></li>
                  <li><a href="product-grid-3-col.html">Products 3 Columns V2</a></li>
                  <li><a href="product-grid-4-col.html">Products 4 Columns</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products List View</li>
                  <li><a href="product_list_left_sidebar.html">Products Sidebar Left</a></li>
                  <li><a href="product-list-right-sidebar.html">Products Sidebar Right</a></li>
                  <li class="listHeading">Others</li>
                  <li class="active"><a href="single_product.html">Single Product</a></li>
                  <li><a href="cart_page.html">Cart Page</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Checkout</li>
                  <li><a href="checkout_step_1.html">Step 1 - Address</a></li>
                  <li><a href="checkout_step_2.html">Step 2 - Shipping</a></li>
                  <li><a href="checkout_step_3.html">Step 3 - Payment</a></li>
                  <li><a href="checkout_step_4.html">Step 4 - Payment</a></li>
                  <li><a href="checkout_complete.html">Order Complete</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <a href="#" class="menu-photo"><%= image_tag("img/menu-photo.jpg", :alt => "menu-img") %></a>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">pages</a>
            <ul class="dropdown-menu dropdown-menu-left">
              <li><a href="about_us.html">About Us</a></li>
              <li><a href="signup.html">Register</a></li>
              <li><a href="signup-login.html">Register or Login</a></li>
              <li><a href="login.html">Login</a></li>
              <li><a href="lost-password.html">Password Recovery</a></li>
              <li><a href="privacy_policy.html">Privacy Policy</a></li>
              <li><a href="terms-and-conditions.html">Terms &amp; Conditions</a></li>
              <li><a href="404.html">404 Not Found</a></li>
              <li><a href="coming-soon.html">Coming Soon</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">blog</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><a href="blog_right_sidebar.html">Right Sidebar</a></li>
              <li><a href="blog_left_sidebar.html">Left Sidebar</a></li>
              <li><a href="blog-fullwidth.html">Full Width</a></li>
              <li><a href="blog-single-fullwidth.html">Single Post</a></li>
              <li><a href="blog_single_right_sidebar.html">Single Right Sidebar</a></li>
              <li><a href="blog_single_left_sidebar.html">Single Left Sidebar</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><a href="account-dashboard.html">Dashboard</a></li>
              <li><a href="account-profile.html">Profile</a></li>
              <li><a href="account-all-orders.html">All Orders</a></li>
              <li><a href="account-single-order.html">Single Order</a></li>
              <li><a href="account-wishlist.html">Wishlist</a></li>
              <li><a href="account-address.html">Address</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
</div>

app/views/layouts/_login_modal.html.erb
<!-- LOGIN MODAL -->
<div class="modal fade login-modal" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/_signup_modal.html.erb
<!-- SIGN UP MODAL -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">新規登録</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">メールアドレス</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">パスワード</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">パスワード（確認用）</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">登録する</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<%= render 'layouts/head' %>
  <body>
    <div class="main-wrapper">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= render 'layouts/copy_right' %>
    </div>
    <%= render 'layouts/login_modal' %>
    <%= render 'layouts/signup_modal' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_categorized_product.html.erb
<div class="col-sm-4 col-xs-12">
  <div class="productBox">
    <%= render partial: 'shared/product', locals: { product: product } %>
  </div>
</div>

app/views/potepan/categories/_sidebar.html.erb
<div class="col-md-3 col-sm-4 col-xs-12 sideBar">
  <%= render partial: "filter/category", locals: { root_taxons: @root_taxons } %>
  <%= render partial: "filter/price" %>
  <%= render partial: "filter/color" %>
  <%= render partial: "filter/size"  %>
</div>

app/views/potepan/categories/show.html.erb
<% provide(:title, page_title(@taxon, @value)) %>
<%= render 'shared/light_section' %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <%= render 'sidebar' %>
      <div class="col-md-9 col-sm-8 col-xs-12">
      <%= render 'filter/area' %>
        <div class="row">
          <%= render partial: 'categorized_product', collection: @category, as: 'product' %>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render 'shared/partners' %>
<%= render 'shared/product_quick_view_modal' %>

app/views/potepan/home/_latest_product.html.erb
<div class="slide">
  <%= render partial: 'shared/product', locals: { product: product } %>
</div>

app/views/potepan/home/_latest_products_section.html.erb
<div class="row featuredProducts">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>新着商品</h4>
    </div>
  </div>
  <div class="col-xs-12">
    <div class="owl-carousel featuredProductsSlider">
      <%= render partial: 'latest_product', collection: @latest_products, as: 'product' %>
    </div>
  </div>
</div>

app/views/shared/_light_section.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= yield(:title) %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "home", potepan_path %>
          </li>
          <li>
            <%= link_to "shop", potepan_category_path(Settings.category[:all_products_id]) %>
          </li>
          <li class="active"><%= yield(:title) %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/shared/_product.html.erb
<div class="productImage clearfix">
  <%= image_tag product.display_image.attachment(:product) %>
  <div class="productMasking">
    <ul class="list-inline btn-group" role="group">
      <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
      <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
      <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
    </ul>
  </div>
</div>
<div class="productCaption clearfix">
  <%= link_to(potepan_product_path(product.id)) do %>
    <h5><%= product.name %></h5>
  <% end %>
  <h3><%= product.display_price %></h3>
</div>